-- =============================================================
-- 01_setup/01_create_database_roles.sql
-- Purpose : One-time environment bootstrap
-- Run as  : ACCOUNTADMIN
-- =============================================================

USE ROLE ACCOUNTADMIN;

-- ─────────────────────────────────────────────
-- 1. VIRTUAL WAREHOUSES
-- ─────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS RETAIL_LOAD_WH
    WAREHOUSE_SIZE   = 'XSMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by Snowpipe & ELT loading jobs';

CREATE WAREHOUSE IF NOT EXISTS RETAIL_TRANSFORM_WH
    WAREHOUSE_SIZE   = 'SMALL'
    AUTO_SUSPEND     = 120
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used for dbt / SQL transformation tasks';

CREATE WAREHOUSE IF NOT EXISTS RETAIL_ANALYTICS_WH
    WAREHOUSE_SIZE   = 'XSMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by BI tools / analysts';

-- ─────────────────────────────────────────────
-- 2. DATABASE & SCHEMAS
-- ─────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS RETAIL_DB
    COMMENT = 'End-to-end retail analytics pipeline';

USE DATABASE RETAIL_DB;

-- Medallion architecture: RAW → STAGING → ANALYTICS
CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Landing zone – raw data exactly as loaded from S3';

CREATE SCHEMA IF NOT EXISTS STAGING
    COMMENT = 'Cleaned, typed, and deduplicated data';

CREATE SCHEMA IF NOT EXISTS ANALYTICS
    COMMENT = 'Dimensional model (dims + facts) for BI consumption';

CREATE SCHEMA IF NOT EXISTS MONITORING
    COMMENT = 'Pipeline health, load history, data quality checks';

-- ─────────────────────────────────────────────
-- 3. ROLES & GRANTS  (principle of least privilege)
-- ─────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS RETAIL_LOADER_ROLE   COMMENT = 'Snowpipe service account – write to RAW only';
CREATE ROLE IF NOT EXISTS RETAIL_ENGINEER_ROLE COMMENT = 'Data engineers – full access to all schemas';
CREATE ROLE IF NOT EXISTS RETAIL_ANALYST_ROLE  COMMENT = 'Analysts – read-only on ANALYTICS schema';

-- Role hierarchy
GRANT ROLE RETAIL_LOADER_ROLE   TO ROLE RETAIL_ENGINEER_ROLE;
GRANT ROLE RETAIL_ENGINEER_ROLE TO ROLE SYSADMIN;

-- Warehouse access
GRANT USAGE ON WAREHOUSE RETAIL_LOAD_WH      TO ROLE RETAIL_LOADER_ROLE;
GRANT USAGE ON WAREHOUSE RETAIL_TRANSFORM_WH TO ROLE RETAIL_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE RETAIL_ANALYTICS_WH TO ROLE RETAIL_ANALYST_ROLE;

-- Database access
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE RETAIL_LOADER_ROLE;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE RETAIL_ENGINEER_ROLE;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE RETAIL_ANALYST_ROLE;

-- Schema-level grants
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE PIPE ON SCHEMA RETAIL_DB.RAW
    TO ROLE RETAIL_LOADER_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK ON SCHEMA RETAIL_DB.STAGING
    TO ROLE RETAIL_ENGINEER_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DB.ANALYTICS
    TO ROLE RETAIL_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA RETAIL_DB.ANALYTICS TO ROLE RETAIL_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES  IN SCHEMA RETAIL_DB.ANALYTICS TO ROLE RETAIL_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS   IN SCHEMA RETAIL_DB.ANALYTICS TO ROLE RETAIL_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB.ANALYTICS TO ROLE RETAIL_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_DB.ANALYTICS TO ROLE RETAIL_ANALYST_ROLE;

-- Monitoring schema
GRANT USAGE ON SCHEMA RETAIL_DB.MONITORING TO ROLE RETAIL_ENGINEER_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DB.MONITORING TO ROLE RETAIL_ENGINEER_ROLE;

